### ISSUE TITLE
Could not initialize class scalaj.http.Http$

### ISSUE THREAD

**Issue by GSManganneau** [scalaj/scalaj-http#100]
Hi there! I am trying to make a request but I got this Error. I am using intellij IDEA and when I run a script i don't this error. Does anybody can help me please? Thanks in advance and sorry for my english.

**Comment by hoffrocket** [comment]
can you post some code that demonstrates the problem?

**Comment by GSManganneau** [comment]
Yeah sure!
`def locateUser (user : User) : User = {
    try {
      val response : HttpResponse[String] = Http("http://opencellid.org/cell/get")
        .param("key", Main.ApiKey)
        .param("mcc", user.mcc_mnc.substring(0, 3))
        .param("mnc", user.mcc_mnc.substring(3))
        .param("lac", user.lac)
        .param("cellid", user.cellId)
        .param("format", "json")
        .asString
      response.throwError
      val body = parse(response.body)
      user.latitude = (body \ "lat").toString
      user.longitude = (body \ "lon").toString
      user.json =
        "{\"imsi\" : " + "\"" + user.imsi + "\" ,\"volume\":" + "\"" + user.volume + "\",\"lon\":" + "\"" + user.longitude + "\" , \"lat\":" + "\"" + user.latitude + "\"" + "}"
    }
    catch{
      case e :NoSuchMethodError  => {
        println (e.getCause)
        println(e.getMessage)
      }
      case e : NoClassDefFoundError => {
        println(e.fillInStackTrace())
        println(e.getStackTrace())
        println(e.getCause())
        println(e.printStackTrace())
        println(e.toString)
      }
    }
    finally {
    }
    return user
  }`

**Comment by GSManganneau** [comment]
I am sorry, I didn't find the good way to print the code. The code "tag" doesn't indent the code properly. Thank you for your help

**Comment by GSManganneau** [comment]
I closed it by accident, I am sorry, it's my first time.

**Comment by hoffrocket** [comment]
the ClassDef and Method errors are probably due to a problem with your classpath. Do you have a dependency declared in your build tool (e.g. sbt, maven, gradle)?

**Comment by GSManganneau** [comment]
Hi! Sorry cause I didn't answer soon and thank you for your time. I wasn't in my office so I couldn't have access to my project and stuff. Yes, I have all the depedencies (maven). The fact is, when I run some unit Test I don't have any error, I am using intelliJ and I really don't understand what's happening here.

**Comment by zhangnew** [comment]
I got this error and solved by change the Scala version. 

Make sure your **Scalaj Http version** match the correct **Scala version**.

Just like that  **scalaj-http_2.11** is match the scala version is 2.11 .

**Comment by futureio** [comment]
If using SBT, change your build.sbt 
```
libraryDependencies += "org.scalaj" %% "scalaj-http" % "2.3.0"
```
