### ISSUE TITLE
Use scala.concurrent.blocking

### ISSUE THREAD

**Issue by shanielh** [scalaj/scalaj-http#102]
I'm not sure if it's needed or not, But currently scalaj-http doesn't wrap IO calls with [scala.concurrent.blocking](https://github.com/alexandru/scala-best-practices/blob/master/sections/4-concurrency-parallelism.md#44-must-use-scalas-blockcontext-on-blocking-io).

**Comment by hoffrocket** [comment]
This library is supposed to be async execution framework agnostic and does not use the scala `Future` library internally.  I think using `blocking` is an optimization that you can choose to use yourself if you're using `Future`
