### ISSUE TITLE
Multiple Parameters on Get

### ISSUE THREAD

**Issue by carnalim** [scalaj/scalaj-http#104]
have an RESTful API call that looks like the following:

`http://xxxxx:9000/api/parameter/value?ecosystem_name=streaming_pipeline&ecosystem_key_name=kafka_brokers`
Which works fine when I use it through postman or Swagger. When I run scalaj-http on it:

```
scala> val result = Http("http://xxxxx:9000/parameter/value").params(Map("ecosystem_name" -> "streaming_pipeline", "ecosystem_key_name" -> "kafka_brokers")).asString
result: scalaj.http.HttpResponse[String] = HttpResponse(,404,Map(Content-Length -> Vector(0), Date -> Vector(Tue, 26 Jul 2016 17:53:49 GMT), Server -> Vector(Apache-Coyote/1.1), Status -> Vector(HTTP/1.1 404 Not Found)))
```

Single Parameters work just fine in my REST calls.

**Comment by carnalim** [comment]
Let me be a little more clear the endpoint is: http://xxxxx:9000/api/parameter/value
The parameters it takes are ecosystem_name, ecosystem_key_name

The server is expecting a get. In swagger and in postman the get works fine with the above URL. the point or what I thought .param/.params was to add in the ?ecosystem_name=streaming_pipeline&ecosystem_key_name=kafka_brokers

**Comment by hoffrocket** [comment]
Yes, that's correct. `.params` should add to the query string:

```scala
scala> scalaj.http.Http("http://httpbin.org/get").params(Map("foo"->"1","bar"->"2")).asString
res2: scalaj.http.HttpResponse[String] = 
HttpResponse({
  "args": {
    "bar": "2", 
    "foo": "1"
  }, 
  "headers": {
    "Accept": "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2", 
    "Accept-Encoding": "gzip,deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "scalaj-http/1.0"
  }, 
  "origin": "1.1.1.1", 
  "url": "http://httpbin.org/get?foo=1&bar=2"
}
,200,Map(Access-Control-Allow-Credentials -> Vector(true), Access-Control-Allow-Origin -> Vector(*), Connection -> Vector(keep-alive), Content-Length -> Vector(327), Content-Type -> Vector(application/json), Date -> Vector(Tue, 26 Jul 2016 19:03:42 GMT), Server -> Vector(nginx), Status -> Vector(HTTP/1.1 200 OK)))
```

**Comment by carnalim** [comment]
Yup it was stupid mistake of my URL being off without the /api.
