### ISSUE TITLE
POST java.net.MalformedURLException: no protocol:

### ISSUE THREAD

**Issue by carnalim** [scalaj/scalaj-http#106]
I am getting the following error, it works just fine in a POST in postman. 

```
java.net.MalformedURLException: no protocol: localhost:9200/node/value/%3C%2Fdts%2Fhdfs%2Ffile%2F%7B%2Fosa%2Fdgtl%2Fmbl%2Fmbl_cal_cust_stacked_dgtl_npi_rfnd%2Finstnc_id%3D20160311180000%2Fpart-m-00046.snappy.parquet%7D%3E/_update
  at java.net.URL.<init>(URL.java:593)
  at java.net.URL.<init>(URL.java:490)
  at java.net.URL.<init>(URL.java:439)
  at scalaj.http.HttpRequest.exec(Http.scala:282)
  at scalaj.http.HttpRequest.execute(Http.scala:270)
  at scalaj.http.HttpRequest.asString(Http.scala:484)
  ... 66 elided
```

Here is what the code looks like: 
`Http(elasticAddress.value + "/node/value/"+ urlEncoded + "/_update").postData(update).header("content-type", "application/json").asString`

**Comment by kypeli** [comment]
What's the value of `elasticAddress.value`? I bet it doesn't include http or https. Just as the error message says.

**Comment by carnalim** [comment]
You are most certainly correct ;) thanks.
