### ISSUE TITLE
Custom Body in Request

### ISSUE THREAD

**Issue by fayimora** [scalaj/scalaj-http#110]
I tried to add a custom body to a `DELETE` request but realised that [the body function](https://github.com/scalaj/scalaj-http/blob/bc3a4908582af59d7190a924591bc2161475c8a5/src/main/scala/scalaj/http/Http.scala#L441) is private. I can't seem to find another function for this. What do I do?

**Comment by hoffrocket** [comment]
You can do this: `Http(url).put(data).method("DELETE")`
That calls `body` internally and then changes the method to `DELETE`

**Comment by fayimora** [comment]
@hoffrocket Thanks. Can I send a PR that states this in the docs?
