### ISSUE TITLE
Support for multipart/related?

### ISSUE THREAD

**Issue by sam** [scalaj/scalaj-http#116]
It doesn't look like a whole lot would have to change to support this?

The use-case is talking to an API, and wanting to POST/PUT some JSON document and a File belonging to that document, in a single request, without encoding the file in a massive Base64 JSON blob.

To make this happen I think it'd just require `MultiPart` to be a sealed trait perhaps that supported non-Binary parts, and a tweak to `MultiPartConnectFunc` that sets the `Content-Type` header to `multipart/related` instead of `multipart/form-data` when non-binary parts are present.

I think.

Does that make sense?

**Comment by hoffrocket** [comment]
Hi,

You can send two pieces of data in one post like this:

```scala
Http("http://httpbin.org/post").postMulti(
  MultiPart("document", "doc.json", "application/json", "{\"a\":\"b\"}".getBytes("utf-8")),
  MultiPart("binaryfile", "binary.file", "application/octet-stream", Array[Byte](1,2,3,4))
).asString
```

Does that work for you?

**Comment by sam** [comment]
There's definitely work-arounds. But I think the deal with `multipart/related` (which I'm certainly no pro on, I just learned about it) is to have different content-types (and not just file mime-types) for each part.

This means (I think), you don't get the bytes for the first part in your example, base64 encode it, assign it to a form-field ("document"), etc. You can have a part with the actual JSON content, not form encoded with Base64 encoded bytes.

See http://stackoverflow.com/a/37394437.

```
POST /upload HTTP/1.1
Host: www.hostname.com
Content-Type: multipart/related; boundary=xyz
Content-Length: [actual-content-length]

--xyz
Content-Type: application/json; charset=UTF-8

{
    "name": "Sample image",
    "desc": "...",
    ...
}

--xyz
Content-Type: image/jpeg

[image data]
[image data]
[image data]
...
--foo_bar_baz--
```

Hopefully that clears things up a bit? So if you need to bulk upload a bunch of photos, you probably want `multipart/form-data`. If you want to upload a *single* image, along with metadata about it, in a single request, then you want `multipart/related`.

I'm not actually sure what server support is like for this. akka-http includes a MediaType for `multipart/related`, but it doesn't have a corresponding model in `Multipart` that I can find (which may just be client stuff; I'm a bit fuzzy on it's usage).

This might help as well: http://www.faqs.org/rfcs/rfc2387.html

For now I guess I'll probably go with your `postMulti` workaround.

**Comment by hoffrocket** [comment]
I could be wrong, but I believe that there is actually no difference in the implementation of a POST with `mulitpart/related` or `mulitpart/form-data` in the top level `Content-Type`.  In both cases, the `Content-Type` of each part can be varied and the actual data is sent as the raw bytes without any base64 encoding.

In any case, correct me if I'm wrong, but I think this might be a theoretical discussion. If the solution that I proposed works for you, it's not a work around, it's the correct and intended usage.

If there is some specific deficiency that prevents the library from supporting your use case, please provide an example and I will be very happy to address.

**Comment by sam** [comment]
AFAICT `MultiPart` only needs a `name` because it's form-encoded. `multipart/related` is for when you don't want/need a form (again, AFAICT).

The "workaround" aspect here is that I'm cramming a `String` that actually represents my JSON payload into a form-field called `"document"` in your example (unless I misunderstand!).

I totally get if you don't want to implement support for this Content-Type. It's certainly your prerogative, and scalaj-http seems flexible enough that I might even be able to hack it in without having to have it "baked in". So that's pretty nice either way.

It could also be that I just misunderstood. You're not using form encoding here, and the only real difference is that the top-level Content-Type says `form-data` instead of `related`?

Either way, I appreciate your patience in discussing this. Like I think I said, this Content-Type is new to me. It just seemed ideal for my use-case of "can I bundle these two requests into one?".

**Comment by hoffrocket** [comment]
That's correct. There is no form encoding. I believe the only difference is the top level `Content-Type`
