### ISSUE TITLE
Support for PATCH

### ISSUE THREAD

**Issue by jaminglam** [scalaj/scalaj-http#117]
Hi, 

Is it possible to support for PATCH?

**Comment by hoffrocket** [comment]
Hi,

You can set the method to `PATCH` like this: `Http("http://httpbin.org/patch").postForm.param("a","b").method("PATCH").asString`

Note that the order of operations is important there. `postForm` changes the method to `POST`, so you need to change the method to `PATCH` after that call.

Does that work for you?

**Comment by jaminglam** [comment]
Hi, @hoffrocket, it works, thanks.
