### ISSUE TITLE
READ.ME oauth example code - unknown parameter

### ISSUE THREAD

**Issue by josephh** [scalaj/scalaj-http#118]
Hi, I copy n pasted the example code in the readme oauth section.

Compiler doesn't recognise  the `token` parameter. 
```scala 
val accessToken = Http("https://api.twitter.com/oauth/access_token").postForm.
  .oauth(consumer, token, verifier).asToken
```
Should the oauth invocation be something like, `oauth(consumer, response.body, verifier)...` ?

**Comment by hoffrocket** [comment]
Yes, thanks for finding and reporting that. Will fix.
