### ISSUE TITLE
Case-insensitive headers

### ISSUE THREAD

**Issue by andrewboni** [scalaj/scalaj-http#120]
Hi there, seems like case-insensitive response headers such as `content-encoding` aren't respected, even though lowercase is valid, [according to the RFC spec](http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive).

[Seems like scalaj-http explicitly looks for `Content-Encoding`](https://github.com/scalaj/scalaj-http/blob/bc3a4908582af59d7190a924591bc2161475c8a5/src/main/scala/scalaj/http/Http.scala#L374) in order to decode or deflate the response body.

Thoughts on supporting case-insensitive headers in general?

**Comment by hoffrocket** [comment]
Hello, the headers map should already be case-insensitive. Do you have an example that demonstrates that's not the case?

This is handled by the specified `Ordering` in the `TreeMap`

**Comment by andrewboni** [comment]
Looks like somehow we were on an old version (`1.1.0`). Updating to the latest `2.3.0` resolved this. Thanks for the quick response.
