### ISSUE TITLE
Request application/json content-type, response returns text/html

### ISSUE THREAD

**Issue by gpage-cs** [scalaj/scalaj-http#121]
I am running my HTTP requests in IntelliJ in an Ubuntu VM.

![html](https://cloud.githubusercontent.com/assets/13422753/22594549/167bebbc-e9e9-11e6-97f8-b6d4c9e68c7a.png)

I have run the request in a curl command and get JSON output as expected.  Other requests run in the same environment as above return JSON output as expected.  The only difference I can see between other requests and the problematic request is the size of the response body; most queries return less than 1000 characters of JSON, the problematic request returns a bit over 25000.

Any ideas or suggestions?

My email is gpage@cognitivescale.com. Thanks for your help.

**Comment by hoffrocket** [comment]
From the response body it looks like you're getting back an api documentation web site. Is it possible that either the URL is incorrect or you're passing in the wrong parameters?

FYI, you've also exposed your apikey in a public forum

**Comment by gpage-cs** [comment]
Thanks Jon.  I'll have to check that.

**Comment by tanel3203** [comment]
Hello,

I have the same question, I'm using scalaj-http 2.3.0.

When performing the GET request `Http(url).asString` in Scala code (same if specifying request content-type as json), the response type is text/html. Using the same url in Postman gives a correct response (just the json response), so it must be something I'm not doing with the request in Scala. Couldn't find an option to limit acceptance type.

//EDIT: As I was writing this, figured it out, when setting header `.header("Accept", "application/json")` on Http, this achieves what is needed. Hopefully this helps someone with the same issue.


Thanks
Tanel

**Comment by laurenemms** [comment]
> Hello,
> 
> I have the same question, I'm using scalaj-http 2.3.0.
> 
> When performing the GET request `Http(url).asString` in Scala code (same if specifying request content-type as json), the response type is text/html. Using the same url in Postman gives a correct response (just the json response), so it must be something I'm not doing with the request in Scala. Couldn't find an option to limit acceptance type.
> 
> //EDIT: As I was writing this, figured it out, when setting header `.header("Accept", "application/json")` on Http, this achieves what is needed. Hopefully this helps someone with the same issue.
> 
> Thanks
> Tanel

Thanks for the edit - this just fixed my issue!
