### ISSUE TITLE
How to disable/customize SSL verifications?

### ISSUE THREAD

**Issue by dluc** [scalaj/scalaj-http#122]
Is it possible to change the trust store or disable SSL verifications?
Could you show the code to make a successful request to 
* https://self-signed.badssl.com
* https://wrong.host.badssl.com
* https://untrusted-root.badssl.com
* https://expired.badssl.com

Thanks

**Comment by hoffrocket** [comment]
Hello, for all of those you can do this: `Http("https://expired.badssl.com").option(HttpOptions.allowUnsafeSSL).asString`
