### ISSUE TITLE
Follow redirect from http to https with status code 307 not working

### ISSUE THREAD

**Issue by dmaicher** [scalaj/scalaj-http#139]
Similar to the original issue reported here (https://github.com/scalaj/scalaj-http/issues/92) a redirect is still not working if the status code is 307 "Temporary Redirect".

Its missing here: https://github.com/scalaj/scalaj-http/blob/master/src/main/scala/scalaj/http/Http.scala#L410

**Comment by seyfer** [comment]
:+1:
