### ISSUE TITLE
Disable automatic decompression?

### ISSUE THREAD

**Issue by daumann** [scalaj/scalaj-http#140]
In my use case I need to forward the payload (gziped) directly to another service.
Is there a way to prevent automatic decompression from gzip upon receiving the response?

**Comment by hoffrocket** [comment]
Yes, `Http(...).compress(false)...`

**Comment by daumann** [comment]
Adding `compress(false)` + a manual `.header("Accept-Encoding", "gzip,deflate")` did the trick. Thanks for the pointer.
