### ISSUE TITLE
I think that the use of content-type with lower case instead of Content-Type could lead to problems

### ISSUE THREAD

**Issue by alex1712** [scalaj/scalaj-http#146]
I think that would not find the content type if the header is written with capital letters, therefor could lead into problems.

https://github.com/scalaj/scalaj-http/blob/4f6574f7cc45dae02e451e9f8d96243ec240b3ea/src/main/scala/scalaj/http/Http.scala#L491

**Comment by hoffrocket** [comment]
the underlying map is case-insensitive, so this is ok

**Comment by alex1712** [comment]
Sorry, maybe I am wrong but if I try this code the result is None:

`
val headers: Map[String, String] = Map(
  "Content-Type" -> "application/json"
)
headers.get("content-type")
`

If you are sure just ignore my comment.

Thanks
