### ISSUE TITLE
An error occurred in the hadoop program

### ISSUE THREAD

**Issue by yueya** [scalaj/scalaj-http#174]
when I send a http request on hadoop the version is 2.4.1 hadoop is 3.1.0:

scala.MatchError: org.apache.hadoop.fs.FsUrlConnection:http:aaa.com (of class org.apache.hadoop.fs.FsUrlConnection)
	at scalaj.http.HttpRequest.scalaj$http$HttpRequest$$doConnection(Http.scala:351)
	at scalaj.http.HttpRequest.exec(Http.scala:343)
	at scalaj.http.HttpRequest.asString(Http.scala:491)

**Comment by hoffrocket** [comment]
I'm not sure what's going on here exactly, but perhaps hadoop is configured
to override the native JDK scheme handler for "http" urls? Note that the
library can not be used for hdfs urls.
See here for reference on how this might be happening within hadoop:
https://stackoverflow.com/questions/26363573/registering-and-using-a-custom-java-net-url-protocol

**Comment by yueya** [comment]
if set sparkSession.sql("set spark.sql.orc.filterPushdown=true")，this error will happen，but the reason i don know 。thanks
