### ISSUE TITLE
How to include a body in a request?

### ISSUE THREAD

**Issue by pligor** [scalaj/scalaj-http#18]
I see you can already have a body (for example json) in a request using "postData" method.
But If I want to perform a DELETE verb/method I start the command like that:

Http(link).option(HttpOptions.method("DELETE")).
  header("Content-Type", "application/json").  ..... ?

How could I include the json body?
Thank you!

**Comment by peter-wolfenden-zocdoc** [comment]
Unfortunately, this limitation (no DELETE bodies) puts a small upper limit on the information which a scalaj client can send to a web API endpoint with DELETE: 8Kb in practice, but [RFC2616 says we cannot assume URLs more than 255 bytes long will be correctly handled](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2.1)).

In practice, API calls with DELETE may need to pass large sets of IDs from the client, which makes it inconvenient to be unable to send a "payload" in the request body; To work around this we must either support DELETE via POST to a new API endpoint (not RESTful), or require the API client to first POST the IDs to a new API endpoint and then pass the returned URI representing this set of IDs to the DELETE endpoint as a URL parameter (RESTful, but inefficient if the set of IDs created is never used again for anything else).

This makes scalaj unattractive for building API clients, and API services which use other API services.

**Comment by hoffrocket** [comment]
Hi, here's an example of a `DELETE` request with data in the body. You do need to specify the `method` after `postData` since `postData` will reset the method to `POST`

Does that work for you? If not, please provide a code example, the output you're seeing, and let me know what you expect the output to be.

```
Http("http://httpbin.org/delete").postData("hello there").method("DELETE").header("content-type","text/text").asString
res3: scalaj.http.HttpResponse[String] = 
HttpResponse({
  "args": {}, 
  "data": "hello there", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2", 
    "Accept-Encoding": "gzip,deflate", 
    "Content-Length": "11", 
    "Content-Type": "text/text", 
    "Host": "httpbin.org", 
    "User-Agent": "scalaj-http/1.0"
  }, 
  "json": null, 
  "origin": "98.113.211.190", 
  "url": "http://httpbin.org/delete"
}
,200,Map(Access-Control-Allow-Credentials -> Vector(true), Access-Control-Allow-Origin -> Vector(*), Connection -> Vector(keep-alive), Content-Length -> Vector(420), Content-Type -> Vector(application/json), Date -> Vector(Sat, 27 Aug 2016 19:54:04 GMT), Server -> Vector(nginx), Status -> Vector(HTTP/1.1 200 OK)))
```

**Comment by hoffrocket** [comment]
If you are seeing the error described in that bug report 

```Exception in thread "main" java.net.ProtocolException: HTTP method DELETE doesn't support output at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1004)```

That bug was fixed 3 years ago, in a pre-release build of Java 8, so just upgrade your JVM.

**Comment by peter-wolfenden-zocdoc** [comment]
@hoffrocket Thank you for the example - it works perfectly in my setup, which is a big relief. And thank you for responsiveness - on a Saturday, no less!

**Comment by chiraglakhani69** [comment]
@hoffrocket Thanks a lot for mentioning "postData will reset the method to POST", otherwise I would have lost at nowhere !!
