### ISSUE TITLE
Base 64 authentication 

### ISSUE THREAD

**Issue by rdatas** [scalaj/scalaj-http#180]
How can I use base64 aithe using scalaj? Is this supported ?

**Comment by hoffrocket** [comment]
Yes, `.auth(user, password` on the HttpRequest.
https://javadoc.io/doc/org.scalaj/scalaj-http_2.12/2.4.1

**Comment by rdatas** [comment]
sorry , was not able to follow. i know how to pass basic auth but would like to use encoded credentials .

here is my basic auth - works fine
val result = Http("http://server1.com:8443/sol/Collection/select?").param("q", "smith").auth("user", "password").asString

here is what i tried but no success 
import scalaj.http.Base64
val result = Http("http://server1.com:8443/sol/Collection/select?").param("q", "smith").auth("user", Base64.encodeString("password")).asString

**Comment by hrj** [comment]
@rdatas 

If you encode the "password" before calling auth, it will get encoded twice. And naturally won't work.

If Base64 was just an example, and you actually want to use some other encoding, then use `header()` function to add a customized `authorization` header. The `auth` function is just a convenience that automatically Base64 encodes the password and then adds the header.
