### ISSUE TITLE
body.asString of a JSON Object

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [scalaj/scalaj-http#191]
When parsing a response of type String
```
val resp = Http("http://....").asString
```
The server answers with HTTP code 200 and with this body:
```
{"par":"value"}
```
but I get instead:
```
Left(Map(par -> value))
```
Who does this strange translation?
It is like the JSON is parsed as a Scala object and then serialized as a string.

**Comment by hoffrocket** [comment]
Hi,

Sorry for late reply, there is no JSON parsing inside this library, so it must be happening somewhere else.

**Comment by DavidPerezIngeniero** [comment]
Thanks for the answer
