### ISSUE TITLE
any reason it still uses sbt 0.13.x instead of 1.2.x?

### ISSUE THREAD

**Issue by Sciss** [scalaj/scalaj-http#192]
Just wondering, since you just use `./build.sbt` and no exotic plug-ins, wouldn't it make sense to move to sbt 1.2.8?

**Comment by hoffrocket** [comment]
No reason, just haven’t had a need to upgrade. Happy to take a PR

**Comment by Sciss** [comment]
Ah - just realising; sbt 1.x uses Scala 2.12, and so requires Java 8. Your travis script uses jdk 7, so that wouldn't work without dropping test builds on jdk 7...
