### ISSUE TITLE
Authentication with bearer token not working

### ISSUE THREAD

**Issue by Sparker0i** [scalaj/scalaj-http#199]
I'm trying to GET an endpoint using curl like this:
```
curl -H "Authorization: Bearer <some auth token>" -H 'Accept: application/json' <some url>
```

But while writing the code for the same in scala using scalaj-http library, it does not work:
```
val response = Http("<that same url>")
    .header("Authorization" , "Bearer " + authToken)
    .header("Accept" , "application/json")
    .asString
    .body

println(response)
```

Above code piece gives me `Invalid authentication token` output in the response, while the curl GET request had no such problems

**Comment by hoffrocket** [comment]
"Invalid authentication token" is a message from the server you're contacting. Guessing that `authToken` does not have the value that you think it has?
