### ISSUE TITLE
Support for hostname validation

### ISSUE THREAD

**Issue by Hakky54** [scalaj/scalaj-http#207]
Currently it is possible already possible to set SSLSocketFactory and possible to add the flag allowUnsafeSSL. But hostname validation is not possible to set within the HttpOptions class. 

This option is available within the HttpsURLConnection class, see here for an example:
```
HostnameVerifier hostnameVerifier = new org.apache.http.conn.ssl.DefaultHostnameVerifier()
HttpsURLConnection httpsURLConnection = (HttpsURLConnection) new URL(https://github.com).openConnection();
httpsURLConnection.setHostnameVerifier(hostnameVerifier);
```

I would like to set HostnameValidation when also setting SSLSocketFactory as it make sense to validate the hostname when ssl is enabled. Whould that be possible to add to ScalaJ?

**Comment by hoffrocket** [comment]
Yes, you can modify the connection this like this:

`Http(url).option(conn => conn. asInstanceOf[HttpsURLConnection].setHostnameVerifier(hv)).asString`

**Comment by Hakky54** [comment]
Ah thank you, I didn't know that the underlying HttpsURLConnection could be manipulated in that way.
It works now!
