### ISSUE TITLE
Custom options

### ISSUE THREAD

**Issue by erickneverson** [scalaj/scalaj-http#208]
Trying to follow your guide to add 3 custom options. Do I have the right idea here?

```
val customOptions: List[HttpOptions.HttpOption] =
      List(c => { "OpenTrack=true" }, c => { "ClickTrack=true" }, c => {
        "UseSystemMAILFROM=false"
      })
```

```
val response: HttpResponse[String] =
      Http("url")
        .timeout(_connTimeoutMs, _readTimeoutMs)
        .method("POST")
        .header("Content-Type", "application/x-www-form-urlencoded")
        .header("Content-Length", message.getBytes.length.toString)
        .options(customOptions)
        .params(params.toSeq)
        .asString
```

**Comment by hoffrocket** [comment]
The `options` are for modifying the underlying `HttpUrlConnection`, which I don't think you want to do.

I'm really not sure what the intention is, but if you have a curl example that works, I can help you translate it.

**Comment by erickneverson** [comment]
You're right, that's not what I need.  I actually realized the options is just another param for the request I'm making.  Thanks for responding.
