### ISSUE TITLE
Question: Does the api throw exceptions?

### ISSUE THREAD

**Issue by psyanite** [scalaj/scalaj-http#210]
Will calling `execute`, `asString`, `asToken`, `asParams` etc. throw any exceptions like timeout exceptions or parse exceptions?

I tried looking through the code but couldn't be sure.

**Comment by hoffrocket** [comment]
Yes, a timeout will bubble up from the underlying socket connection. Parse exceptions will also bubble up as exceptions from the underlying libraries that used-- Probably `NoSuchElementException` for asToken.

**Comment by psyanite** [comment]
@hoffrocket, wow! thanks for asking so quickly. As a suggestion, @throws exception annotations could be added to the methods to prevent users asking again in the future. Have a great day 🌤️
