### ISSUE TITLE
scalaj.http.HttpResponse does not take type parameters

### ISSUE THREAD

**Issue by wiazur** [scalaj/scalaj-http#212]
I've tried to run the line suggested for a GET request, but getting this error:

```
command-342129021467143:3: error: scalaj.http.HttpResponse does not take type parameters
val response: HttpResponse[String] = Http("http://api.worldbank.org/v2/country/{}?format=json").param("country").asString
```

Not shown is that there is a caret "^" beneath the `HttpResponse[String]`. So I guess it doesn't like `HttpResponse[String]`.

Here is my code:

```
import scalaj.http.{Http, HttpResponse}

val response: HttpResponse[String] = Http("http://api.worldbank.org/v2/country/{}?format=json").param("country").asString

println(response.body)
```

**Comment by fntz** [comment]
Hello,
I tried your example, but I got another error:

```
error: not enough arguments for method param: (key: String, value: String)scalaj.http.HttpRequest.
Unspecified value parameter value
``` 

after providing a key-value pair to `param` method, I got success response & compilation

**Comment by wiazur** [comment]
Thanks, I also didn't realize using a pipeline was affecting things. I'm using Azure Databricks and Spark, so there are other specifications needing to be considered. Good to know you got it to work though.

**Comment by fntz** [comment]
I propose to pass the full namespace :

```
val response: scalaj.http.HttpResponse[String] = ???
```

because otherwise maybe you have mixed `HttpResponse` from somewhere else
