### ISSUE TITLE
Multipart is missing the dataparts

### ISSUE THREAD

**Issue by pligor** [scalaj/scalaj-http#42]
How could someone implement the data parts of a multipart ?

These are a seperate section from files.

For example my web service framework is using a method like `multipartBody.dataParts("some key in here")` to get data parts and `multipartBody.file("filename")` to get files.

To make more clear what I am talking about I will note this from official specificaiton: A form data part of a multipart looks like that at the end (if boundary is *****):

```
--*****
Content-Disposition: form-data; name="some name"\n
\n
value here\n
\n
```

**Comment by alpeb** [comment]
Seems like I can't use `postData` and `multipart` together (I'm trying to send a json payload along with a file) :-(

**Comment by hoffrocket** [comment]
Yes, postData and multipart conflict with each other, but you can send more than one part.

scalaj-http 1.x.x:
```scala
Http(url).postMulti(mp1, mp2)
```

scalaj-http 0.3.x:
```scala
Http.postmulti(url, mp2, mp2)
```

**Comment by alpeb** [comment]
But each part is only for files, not raw content, right?

**Comment by hoffrocket** [comment]
I could be wrong, but I don't think the http spec allows for raw content along with multipart. Please point me toward specification docs or the docs for the service you are trying to interact with if you think otherwise. You can probably work around by issuing two separate requests if you need the json payload to be raw.

**Comment by alpeb** [comment]
I don't know, maybe rfc2388? This is for an internal service at my company, but I've done this before with jquery, posting both data and files. Here's an example of apache's httpcomponents lib doing that:
http://hc.apache.org/httpcomponents-client-ga/httpmime/examples/org/apache/http/examples/entity/mime/ClientMultipartFormPost.java

**Comment by hoffrocket** [comment]
Ah, I see the http component library allows you to add a part without a file name. It might work with an empty filename. Have you tried something like this?

```scala
Http(url).postMulti(
  MultiPart(name="file", filename="foo.jpg", mime="image/jpeg", data=bytes),
  MultiPart(name="json", filename="", mime="application/json", data="{}")
)
```

**Comment by hoffrocket** [comment]
You might also be able to do this:

```scala
Http(url)
  .postMulti(MultiPart(name="file", filename="foo.jpg", mime="image/jpeg", data=bytes))
  .param("json", "{}")
```

If neither of those things work, I can make a change to allow filename to be optional on the MultiPart

**Comment by alpeb** [comment]
Ok, I think I have a better understanding of this. I can just use MultiPart with an empty filename and convert the json payload into an InputStream to conform with the API. Thanks!
