### ISSUE TITLE
content-encoding

### ISSUE THREAD

**Issue by mhow** [scalaj/scalaj-http#59]
twitter is sending the content-encoding header in lower case and this isn't being detected by scalaj (unless I'm doing something wrong).  This means that for twitter I am decoding manually but for facebook no problem.

Can it (should it) be made case insensitive?

**Comment by hoffrocket** [comment]
Can you send some example code that illustrates the problem?

**Comment by fntzr** [comment]
this work fine.

scalaj-http get headers in this [line](https://github.com/scalaj/scalaj-http/blob/master/src/main/scala/scalaj/http/Http.scala#L330) if we see on source of `HttpURLConnection` 
class we might see that for headers ignore case [link](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/net/www/MessageHeader.java#86)

I try in console with latest scalaj-http and

```scala
import scalaj.http._
import scalaj.http._

scala> val u = "https://twitter.com"
u: String = https://twitter.com

scala> val r = Http(u).asString
r: scalaj.http.HttpResponse[String] =  HttpResponse(...
scala> r.headers
res0: Map[String,String] = Map(x-transaction -> 864a307e1699ffc2, expires -> Tue, 31 Mar 1981 05:00:00 GMT, x-ua-compatible -> IE=edge,chrome=1, server -> tsa_b, x-xss-protection -> 1; mode=block, x-response-time -> 12, cache-control -> no-cache, no-store, must-revalidate, pre-check=0, post-check=0, content-security-policy -> default-src https:; connect-src https:; font-src https: data:; frame-src https: twitter:; img-src https: data:; media-src https:; object-src https:; script-src 'unsafe-inline' 'unsafe-eval' https:; style-src 'unsafe-inline' https:; report-uri https://twitter.com/i/csp_report?a=NVQWGYLXFVZXO2LGOQ%3D%3D%3D%3D%3D%3D&ro=false;, content-length -> 13374, x-connection-hash -> ed4a763b545340b662c7f75330e7ee10, last-modified -> Wed, 28 Jan 2015 20:54:20 GMT, date -> Wed, 28...
scala> 

scala> r.headers.keys.filter(x => x.contains("content"))
res2: Iterable[String] = Set(content-security-policy, content-length, content-type, x-content-type-options, content-encoding)
```

as you can see this include `content-encoding` in downcase.

**Comment by mhow** [comment]
When I run this code
val config = ConfigFactory.load()

     val req = Http("https://api.twitter.com/1.1/followers/ids.json").header("Authorization",
"Bearer " + config.getString("semeon.api.twitter.api.auth"))
            .header("User-Agent", "SemeonAnalytics
Engagement").header("Accept-Encoding", "gzip,deflate")
            .params("user_id" -> "40559231", "include_entities" -> "true",
"count" -> "5000")
            .option(HttpOptions.readTimeout(60000))
            .option(HttpOptions.connTimeout(10000))
     val resp = req.asString

     Console.println(resp.headers)
     Console.println(resp.body)

(you will need your own twitter auth)

I get this output:
Map(x-transaction -> dd7e4e074cc2d889, expires -> Tue, 31 Mar 1981 05:00:00
GMT, server -> tsa_b, x-xss-protection -> 1; mode=block, x-rate-limit-reset
-> 1422481508, x-response-time -> 14, cache-control -> no-cache, no-store,
must-revalidate, pre-check=0, post-check=0, content-length -> 127,
x-connection-hash -> 5400c3d2f8419a941ea07bf531ab74da, last-modified ->
Wed, 28 Jan 2015 21:30:08 GMT, date -> Wed, 28 Jan 2015 21:30:08 UTC,
x-rate-limit-limit -> 15, x-rate-limit-remaining -> 14, content-type ->
application/json;charset=utf-8, status -> 200 OK, x-access-level -> read,
pragma -> no-cache, set-cookie -> guest_id=v1%3A142248060882924196; Domain=.
twitter.com; Path=/; Expires=Fri, 27-Jan-2017 21:30:08 UTC,
x-twitter-response-tags -> BouncerCompliant, x-frame-options -> SAMEORIGIN,
x-content-type-options -> nosniff, strict-transport-security ->
max-age=631138519, Status -> HTTP/1.1 200 OK, content-encoding -> gzip)
�

If I get the response as bytes and gunzip it manually I get the correct
output.

**Comment by hoffrocket** [comment]
got it, the headers should be case-insensitive. i'll create fix. thanks for the bug report!

**Comment by hoffrocket** [comment]
i just pushed version 1.1.1 with the fix to the oss maven repo.
