### ISSUE TITLE
POST with url query parameters and body

### ISSUE THREAD

**Issue by mhow** [scalaj/scalaj-http#61]
This may not fit the design of the library but I need to send a POST that has both query parameters and  a body.  I couldn't figure out how to accomplish this.  I have managed query parameters on a POST but as soon as I add a body the query parameters disappear.

wanting something like this http://www.bla.com/url/path?param1=something&param2=somethingelse
with content-type=application/json in the body.

Thanks

**Comment by hoffrocket** [comment]
Thanks again for the bug reports. Released 1.1.3 with the fix

**Comment by arjunjun4u** [comment]
Hi @hoffrocket ,

I am trying to make a PUT request with query params and body content and it seems to me the end 
request doesn't retain the query params. 

1. I tried with v 1.1.3 and 1.1.4
2. POST request has the same issue as well
3. GET request works (got a valid response as the parameter is the auth token)

Code snippet:
Http(endpointUrl).postForm(bodyArgs.toSeq).method("PUT").params(paramMap).headers(headersSeq).option(HttpOptions.followRedirects(true))

Any pointers? 

Thanks
Arjun

**Comment by arjunjun4u** [comment]
The workaround I did was to serialize the map object into json string and use postData instead of postForm.
