### ISSUE TITLE
1.1.3 breaks the content-encoding header case insensitivity

### ISSUE THREAD

**Issue by mhow** [scalaj/scalaj-http#62]
Running with 1.1.3 I started getting gzipped bytes from twitter again.  switching back to 1.1.1 I get strings.  Looks like the 1.1.3 somehow broke the content-header case insensitivity.

**Comment by hoffrocket** [comment]
sorry about that. i released 1.1.4 with a fix

**Comment by mhow** [comment]
Thanks,  Love the really fast turnaround.

Matthias
