### ISSUE TITLE
Adding this library to library dependencies results in ClassNotFoundException for the App object

### ISSUE THREAD

**Issue by luminescent** [scalaj/scalaj-http#63]
Hi 

I have a project seeded from here: https://github.com/spray/spray-template

I have added this line to my librariesDependencies:    "org.scalaj"          %%  "scalaj-http"       % "1.1.4" and now I get a runtime error Exception in thread "main" java.lang.ClassNotFoundException: com.example.Boot 

This is the Boot object: 

object Boot extends App {
...
}
where App is scala.App
 
As soon as I remove the line from libraries dependencies, everything runs fine again. I don't even have to add a call to something from scalaj, it just immediately breaks when I add this as a dependency. 

Other dependencies I have are: 
    "io.spray"            %%  "spray-can"         % sprayV,
    "io.spray"            %%  "spray-routing"     % sprayV,
    "io.spray"            %%  "spray-testkit"     % sprayV  % "test",
    "io.spray"            %%  "spray-json"        % "1.3.1",
    "com.typesafe.akka"   %%  "akka-actor"        % akkaV,
    "com.typesafe.akka"   %%  "akka-testkit"      % akkaV   % "test",
    "org.specs2"          %%  "specs2-core"       % "2.3.11" % "test",
    "com.typesafe.slick"  %%  "slick"             % "2.1.0",
    "com.typesafe.slick"  %%  "slick-extensions"  % "2.1.0",
    "c3p0"                %   "c3p0"              % "0.9.1.2",
    "org.slf4j"           %   "slf4j-api"         % "1.7.10",
    "org.slf4j"           %   "slf4j-simple"      % "1.7.10"

**Comment by hoffrocket** [comment]
I don't think your problem is related to scalaj-http, but maybe just an sbt issue?
Try killing your current sbt shell, and then running "clean", "compile" and "re-start"

**Comment by luminescent** [comment]
This was indeed the issue. Thank you.
