### ISSUE TITLE
Host headers can't be set

### ISSUE THREAD

**Issue by davesmith00000** [scalaj/scalaj-http#64]
Love this library and use it for everything, but I've hit a weird edge case that prevents me from using it in one particular case.

For reasons I won't go into, I have no DNS lookup available so I have to use the IP address, and the service I'm trying to reach is on a subdomain. I've deduced that the way around this using curl or some other posting tool is to set the host header to what would be the subdomain.domain.tld I'd like to reach.

Attempting to set the host header using the header method does not work, apparently this is a security feature of the underlying java library. Ok fair enough.

I tried the same trick with another library (Play's WS) and setting the host is also not allowed there, however, they provide a method called withVirtualHost("subdomain.domain.tld") and that does the magic.

I'd love it if something similar appeared in this library so I can ditch WS! :)

If I get some time I might have a go but it's unlikely :( so I thought I should capture this in an issue.

**Comment by hoffrocket** [comment]
That is an annoying restriction of the java libraries. You can workaround by doing one of the following:
Start your JVM with this command line parameter: ``` -Dsun.net.http.allowRestrictedHeaders=true```
or, do this first thing at runtime: ```System.setProperty("sun.net.http.allowRestrictedHeaders", "true")```

Does that work for you?

**Comment by davesmith00000** [comment]
Worked like a charm - thanks! Might be worth sticking in the docs and / or encapsulating in an HttpOption or something? Just a thought. Thanks for the help though and keep up the good work, the last update (to 1.1.0) was excellent!

**Comment by hoffrocket** [comment]
i've updated the docs, thanks!
