### ISSUE TITLE
DNS exception not managed 

### ISSUE THREAD

**Issue by Dnomyar** [scalaj/scalaj-http#68]
First, thanks for you work !

When I try to use this lib with an incorrect URL, it blocks. 
I can see, with Wireshark, the dns response error : No such name.
I have solved the problem by adding a try/catch (see below). 
It's a little bit ugly, but it seems to work.

```scala
def exec[T](parser: (Int, Map[String, String], InputStream) => T): HttpResponse[T] = {
    val urlToFetch: URL = new URL(urlBuilder(this))
    try{
      proxyConfig.map(urlToFetch.openConnection).getOrElse(urlToFetch.openConnection) match {
        case conn: HttpURLConnection =>
          conn.setInstanceFollowRedirects(false)
          HttpOptions.method(method)(conn)
          if (compress) {
            conn.setRequestProperty("Accept-Encoding", "gzip,deflate")
          }
          headers.reverse.foreach{ case (name, value) =>
            conn.setRequestProperty(name, value)
          }
          options.reverse.foreach(_(conn))

          connectFunc(this, conn)
          try {
            toResponse(conn, parser, conn.getInputStream)
          } catch {
            case e: java.io.IOException if conn.getResponseCode > 0 =>
              toResponse(conn, parser, conn.getErrorStream)
          } finally {
            closeStreams(conn)
          }
      }
    }catch{
      case e: Exception =>
        HttpResponse(e.asInstanceOf[T], 502, Map())
    }
  }
```

**Comment by hoffrocket** [comment]
Could you send an example HttpRequest that illustrates the problem? I'm not sure exactly what you mean by "incorrect url" and "blocks"

**Comment by Dnomyar** [comment]
Sorry, I have forgotten to specify that I am working with concurrency.
Here is an example of code that illustrate this problem : 
```scala
package controllers

import play.api._
import play.api.mvc._

import scalaj.http._

import scalaz._
import scala.concurrent._

import scala.concurrent.ExecutionContext.Implicits.global


object Application extends Controller {

  def test = Action {
    processLongAsyncTask
    Ok("Ok")
  }

  def processLongAsyncTask: Future[String\/String] = Future {
    println("SENT")
    val response: HttpResponse[String] = Http("http://www.leboncoinsdfazf.fr/").asString
    println(response.toString)
    \/-("Ok")
  }
}
```

I try to ping the incorrect URL : 
```
$ ping http://www.googlazdazdazd.fr/ 
ping: unknown host http://www.googlazdazdazd.fr/
```
I go to [http://localhost:9000/test](http://localhost:9000/test), this is what I see in the logs : 
```
--- (RELOAD) ---

[info] play - Application started (Dev)
SENT
```
After "SENT" it should print the response but, as you can see, there is nothing.

**Comment by hoffrocket** [comment]
Hi, sorry for the delayed response. I don't think this is an issue the the Http library and I'm not well versed in the other libraries you're using. The expected behavior of the Http library is to throw an `UnknownHostException`. To isolate things and aid with your testing, you can just throw expected exception without using the library and see what happens:

```scala
  def processLongAsyncTask: Future[String\/String] = Future {
    println("SENT")
    throw new java.net.UnknownHostException("www.googlazdazdazd.fr")
    println(response.toString)
    \/-("Ok")
  }
```

If explicitly throwing the exception doesn't exhibit the same behavior as when using the Http library, please capture a thread dump and send it to me. On a unix system you can "kill -QUIT <pid>" and the thread dump should output to STDERR.
