### ISSUE TITLE
How to add data into a GET request?

### ISSUE THREAD

**Issue by zacker330** [scalaj/scalaj-http#69]
Hi guy. 
how to implement this below:
GET /my_index/my_type/_search
{
    "query": {
        "match": {
             "title": "QUICK!"
           }
     }
}

**Comment by hoffrocket** [comment]
The library does not support sending data in the body of a GET request. Is that what you want? You can POST string data using ```Http(url).postData("...")```.

**Comment by zacker330** [comment]
@hoffrocket  got you. that's my fault. Thanks.
