### ISSUE TITLE
What happened to HttpException ?

### ISSUE THREAD

**Issue by pligor** [scalaj/scalaj-http#71]
Hi there! After a long time I have decided to upgrade to the latest (1.1.4) version from 0.3.x

On the old version of scalaj I used to have a line that looked like that
```
case e: HttpException => MyCustomErrorResultCaseClass(e.body, e.message)
```

Is HttpException used at all in the latest version? I only see it referenced once in the source code

**Comment by hoffrocket** [comment]
`HttpException` is not used at all anymore. I'll remove it from the library to avoid confusion. It was formally used for HTTP 4xx and 5xx responses.  Those are no longer considered Exception worthy, you can check the `HttpResponse` for the response code or use a helper method like `response.isError`.

IO exceptions from the underlying `java.net.HttpURLConnection` will be thrown unadulterated.

See docs here: http://scalaj.github.io/scalaj-http/1.1.0/#scalaj.http.HttpResponse 

More differences from 0.3.x are mentioned in the README
