### ISSUE TITLE
Multipart uploading files larger than 2Go: negative long returned

### ISSUE THREAD

**Issue by takiri** [scalaj/scalaj-http#72]
Hi, thanks for this lib!

This issue is related to a previous one: #38.
I explained then that I couldn't uplaod files of >2Go using multipart. That was fixed but there's still a problem:
the Long (length written) returned and handled by writeCallBack: Long => Unit is negative and decreasing after 2Go (2147483648 as Long) has been reached. 
It should still be growing until reaching the file length.

I upgraded to version 1.1.4.

**Comment by hoffrocket** [comment]
I just pushed a 1.1.5 release with the fix. Thanks!
