### ISSUE TITLE
when running req.exec resultparser is called twice

### ISSUE THREAD

**Issue by mhow** [scalaj/scalaj-http#75]
Not sure what I am doing wrong.

code looks like this:
val req = Http("http://someurl.com").header("Authorization",buildBasicAuth("thing","otherthing")))
        .header("Accept-Engoding","gzip").header("Keep-Alive","true").header("Accept","application/json")
val resp = req.exec(resultParser)
with the first few lines of resultParser:
    def resultParser(resCode:Int, headers:Map[String,String], stream:InputStream):HttpResponse[String]= {
        logger.info("In result parser!")
        logger.info("rescode:{}",resCode)

In the tracing I get:
INFO 2015-08-12 16:27:37.340 [Streaming-akka.actor.default-dispatcher-3] StreamingActor 154 - In result parser!
INFO 2015-08-12 16:27:37.341 [Streaming-akka.actor.default-dispatcher-3] StreamingActor 158 - rescode:200
INFO 2015-08-12 16:27:43.264 [Streaming-akka.actor.default-dispatcher-3] StreamingActor 154 - In result parser!
INFO 2015-08-12 16:27:43.268 [Streaming-akka.actor.default-dispatcher-3] StreamingActor 158 - rescode:200

And when I try to access the stream it is closed.

Thanks

**Comment by hoffrocket** [comment]
I'm also not sure what's going on with the code above. Can you send minimal runnable piece of code that illustrates the problem? My attempt indicates that the parser is only called once:

```scala
scala> Http("https://www.google.com/").exec((code, headers, is) => { println(s"Parser got code $code") }).body
Parser got code 200
```

**Comment by hoffrocket** [comment]
Also, your log statements are 6 seconds are apart which suggests that you're calling the entire block of code twice

**Comment by mhow** [comment]
Just double checked the log times - re ran it  - got :
INFO 2015-08-12 16:49:31.658 [Streaming-akka.actor.default-dispatcher-3]
StreamingActor 43 - In result parser!
INFO 2015-08-12 16:49:31.659 [Streaming-akka.actor.default-dispatcher-3]
StreamingActor 44 - rescode:200
INFO 2015-08-12 16:49:31.664 [Streaming-akka.actor.default-dispatcher-3]
StreamingActor 43 - In result parser!
INFO 2015-08-12 16:49:31.664 [Streaming-akka.actor.default-dispatcher-3]
StreamingActor 44 - rescode:200

Not sure how it could get called twice in this scenario without other logs
also getting duplicated.

I will continue to poke - if I can get it replicatable I'll send it along -
thanks for the very quick responses.

**Comment by mhow** [comment]
import java.io.InputStream
import scalaj.http.HttpResponse
import org.slf4j.LoggerFactory
import scala.io.Source
import scalaj.http.Http

object StreamPlay extends App {

  val logger = LoggerFactory.getLogger("StreamPlay")
  val req = Http("https://www.google.com/").exec(resultParser)

  def resultParser(resCode:Int, headers:Map[String,String],
stream:InputStream):HttpResponse[String]= {
        logger.info("In result parser!")
        logger.info("rescode:{}",resCode)
        val res =  Source.fromInputStream(stream).mkString
        new HttpResponse(res, resCode, headers)

  }
}

this worked fine - so it must be something with the way the actors are
running it - most likely something I've messed up somewhere.

close away.

Thanks

**Comment by mhow** [comment]
In the exec method it does get called twice.
First time with the conn.getInputStream, the second time with the
conn.getErrorStream - so gets an exception and after trying the first call
then does the second one.  So the problem is with the original stream -
I'll need to check the exception - see what goes on.

This is just for anyone else's future reference - can't say if this
behaviour is wrong or not.

**Comment by mhow** [comment]
Solved in the end.  Problem was I was wrapping the incoming stream with a
GZIPInputStream - but it was already taken care of.  This library makes
life simpler. thanks.

**Comment by hoffrocket** [comment]
Ah, yes, the same parser is used if there's an IO error
