### ISSUE TITLE
v1.1.5 breaks semantic versioning

### ISSUE THREAD

**Issue by mfulgo** [scalaj/scalaj-http#78]
Hi Jon,

Not sure if you care, but there are API-breaking changes between versions 1.1.4 and 1.1.5:
 - Removing the `HttpException` class
 - Changing the name and type of `HttpRequest.proxy` and `BaseHttp.proxy`

If you're trying to follow [semantic versioning](http://semver.org), the release should have been 2.0.0.

Also, a quick observation on `HttpRequest.proxy(proxy: Proxy)`: You're using `copy(proxyConfig = Some(proxy))` which means there's not an easy way to un-set the proxy.  If you used `copy(proxyConfig = Option(proxy)` instead, users could pass in `null` to un-set it.  Alternatively, to avoid nulls, you could provide a `def proxyConfig(proxyConfig: Option[Proxy])` method.

Best,
-Matt

**Comment by hoffrocket** [comment]
Thanks for the feedback. I'll try to follow semantic versioning more carefully in the future to signal breaking changes. If you are looking for a way to unset the proxy I believe you could use `.copy(proxyConfig = None)`. Maybe it's worth adding another method though. Has that been a annoyance for you?

**Comment by mfulgo** [comment]
Nah, it wasn't an annoyance, just an observation since you were already providing wrappers around copy functionality. On that topic however, the thing that we've found ourselves doing is to provide helpers for get/post/put/etc.  I'll see about getting approval to contribute the enhancements.

The bigger issue here was the API break. I'll go ahead and close this since I'm guessing you don't want to revert, release a fixed 1.1.6, re-add the changes, and release a 2.0.0.  =D
