### ISSUE TITLE
Don't send headers when redirect occurs

### ISSUE THREAD

**Issue by josete89** [scalaj/scalaj-http#80]
When I realized a hit post operation or whatever that finalize with a redirection, the previous headers won't be send and the redirect response miss the cookie.

**Comment by hoffrocket** [comment]
Hi,

Could you send a code example that illustrates this problem?

**Comment by josete89** [comment]
val s = Http("someURL").asString

    val cookie = s.headers("Set-Cookie")


    var response2 = Http("someURL")
        .header("Set-Cookie",cookie)
        .option(HttpOptions.followRedirects(true))
        .postForm(Seq("ctl00$content$searchjobs$txtSearchJobs\"" -> "madrid", "\"ctl00$content$searchjobs$btnSearchJobs" -> "0")).asString

**Comment by hoffrocket** [comment]
Hi,

You are using the wrong header name. It should be "Cookie" in the request, not "Set-Cookie". 

See here:

```
scala> Http("https://httpbin.org/redirect/1").header("Cookie","bar").option(HttpOptions.followRedirects(true)).asString.body
res4: String = 
"{
  "args": {}, 
  "headers": {
    "Accept": "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2", 
    "Accept-Encoding": "gzip,deflate", 
    "Cookie": "bar", 
    "Host": "httpbin.org", 
    "User-Agent": "scalaj-http/1.0"
  }, 
  "origin": "207.110.15.222", 
  "url": "https://httpbin.org/get"
}
"
```
