### ISSUE TITLE
Adding a section on OAuth?

### ISSUE THREAD

**Issue by liangzan** [scalaj/scalaj-http#81]
Hi,

I've been burnt by this. If the request is not a GET I have to set the HTTP method before I sign my request in order to get the correct signature.

``` scala
val request = Http(url)
request
  .method("POST") // set this first before oauth
  .oauth(consumer, accessToken)
```

Could you have it in the readme so that others will take note? Otherwise this is a wonderful library to use. Thanks.

**Comment by hoffrocket** [comment]
Yes, the .oauth call must be the last thing. That could be changed though. Thanks for the feedback, I'll add an issue for that and update the docs in the meantime.
