### ISSUE TITLE
Duplicate headers should not be joined with comma

### ISSUE THREAD

**Issue by ptxmac** [scalaj/scalaj-http#83]
Current scalaj-http joins duplicate headrs with a comma. This is a big problem when parsing cookies.
If a page sets multiple cookies, they will be send as duplicate `Set-Cookie:` headers.

A cookie header contains a `expires` field which is a human readable date containing a comma.

e.g.

```
Set-Cookie: Some_login=35; path=/; expires=Fri, 01-Jan-2038 00:00:00 GMT; HttpOnly
Set-Cookie: Some_logincookie=asd123; path=/; expires=Fri, 01-Jan-2038 00:00:00 GMT; HttpOnly
```

scalaj-http will join this as
`Some_login=35; path=/; expires=Fri, 01-Jan-2038 00:00:00 GMT; HttpOnly, Some_logincookie=asd123; path=/; expires=Fri, 01-Jan-2038 00:00:00 GMT; HttpOnly`

Now it's impossible to get back the original values. Splitting on `,` as a separator will result in 4 values because the timestamp include commas.

**Comment by hoffrocket** [comment]
thanks. i'll push out a 2.0.0 release soon for this.

**Comment by ptxmac** [comment]
Awesome!

**Comment by hoffrocket** [comment]
i just pushed out the 2.0.0 release
