### ISSUE TITLE
Make cross-platform (i.e. support Scala.JS)?

### ISSUE THREAD

**Issue by bbarker** [scalaj/scalaj-http#85]
I'm not suggesting that this be done by the existing authors, but am rather curious if they would support it if successfully completed. Note the [entailed restructuring](http://www.scala-js.org/doc/project/cross-build.html).

Thanks,

**Comment by omidb** [comment]
you can look at #84

**Comment by bbarker** [comment]
Ah, looks like I forgot to search closed issues - thanks!

On Mon, Nov 30, 2015 at 1:23 PM, Omid Bakhshandeh <notifications@github.com>
wrote:

> you can look at #84 <https://github.com/scalaj/scalaj-http/issues/84>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalaj/scalaj-http/issues/85#issuecomment-160714203>.
>



-- 
Brandon Barker
brandon.barker@gmail.com
