### ISSUE TITLE
BaseHttp clears proxyConfig in it's apply() method

### ISSUE THREAD

**Issue by ajrnz** [scalaj/scalaj-http#86]
Is there any reason `BaseHttp` sets `proxyConfig` to `None` instead of copying it in it's `apply()` method?

I want to do something like:

    val proxy = if (useProxy)) {
      val addr = new InetSocketAddress(proxyHost, proxyPort)
      Some(new java.net.Proxy(java.net.Proxy.Type.HTTP, addr))
    }
    else None

    val myHttp = new BaseHttp(proxy)

so that I can then just use myHttp in the future with out worrying about whether a proxy is enabled. Currently it is cleared and doing `myHttp(url)` removes the proxy

Is there a better way of doing this?

**Comment by hoffrocket** [comment]
Hi, thanks for reporting this. You just uncovered a bug. `BaseHttp` does not pass the `proxyConfig` to the `HttpRequest`. I'll push a fix and patch release. In the meantime, you can set proxy on each instance of `HttpRequest`.

**Comment by hoffrocket** [comment]
version 2.2.1 with the fix should be out in the maven repos
