### ISSUE TITLE
sudden handshake_failure making requests to paypal sandbox

### ISSUE THREAD

**Issue by kipperjim** [scalaj/scalaj-http#88]
I last successfully made a request to a paypal rest api (https://svcs.sandbox.paypal.com/AdaptivePayments/Pay) on 19 Jan, however today I am receiving the appended stack trace.

I don't really know where to start looking, however I use your library for making http requests so here I am :)  I was using an older version of your library however I upgraded to 2.2.1 to retry and the problem still exists for this version of your library.

The url above can be called to show the below failure without headers and content because it fails before these are necessary.

Do you think this is a problem on your end?  

My code is simply

scalaj.http.Http("https://svcs.sandbox.paypal.com/AdaptivePayments/Pay").option(HttpOptions.connTimeout(1000)).option(HttpOptions.readTimeout(5000)).asParams

Let me know if any more info is helpful.

Many thanks!

Received fatal alert: handshake_failure
sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1959)
sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1077)
sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339)
sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323)
sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
scalaj.http.BaseHttp$$anonfun$apply$8.apply(Http.scala:692)
scalaj.http.BaseHttp$$anonfun$apply$8.apply(Http.scala:692)
scalaj.http.HttpRequest.exec(Http.scala:347)
scalaj.http.HttpRequest.execute(Http.scala:322)
scalaj.http.HttpRequest.asParams(Http.scala:539)
code.cardpayment.Paypal$.createPayment(Paypal.scala:68)
code.services.OnlinePaymentService$class.setUpPayment(OnlinePaymentService.scala:54)
code.cardpayment.Paypal$.setUpPayment(Paypal.scala:13)
code.database.Booking.saveNewBooking(Booking.scala:210)
code.pac.MatchingJourneysAgent.setupPayment(MatchingJourneysAgent.scala:239)
code.comet.MatchingJourneysCometActor$$anonfun$lowPriority$1$$anonfun$applyOrElse$3.apply(MatchingJourneysCometActor.scala:34)
code.comet.MatchingJourneysCometActor$$anonfun$lowPriority$1$$anonfun$applyOrElse$3.apply(MatchingJourneysCometActor.scala:34)
net.liftweb.http.CometActor$$anonfun$net$liftweb$http$CometActor$$_mediumPriority$1.applyOrElse(CometActor.scala:972)
scala.PartialFunction$OrElse.apply(PartialFunction.scala:162)
scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
scala.collection.AbstractMap.applyOrElse(Map.scala:58)
scala.PartialFunction$OrElse.apply(PartialFunction.scala:162)
scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
scala.collection.AbstractMap.applyOrElse(Map.scala:58)
scala.PartialFunction$OrElse.apply(PartialFunction.scala:162)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply$mcV$sp(CometActor.scala:715)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply(CometActor.scala:713)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$apply$mcV$sp$3.apply(CometActor.scala:713)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$class.functionLifespan(S.scala:1746)
net.liftweb.http.S$.functionLifespan(S.scala:47)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(CometActor.scala:713)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(CometActor.scala:713)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(CometActor.scala:713)
net.liftweb.util.AnyVarTrait$class.doWith(AnyVar.scala:234)
net.liftweb.util.AnyVar.doWith(AnyVar.scala:89)
net.liftweb.http.RenderVersion$$anonfun$doWith$1.apply(LiftSession.scala:471)
net.liftweb.common.EmptyBox.openOr(Box.scala:701)
net.liftweb.http.RenderVersion$.doWith(LiftSession.scala:471)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(CometActor.scala:712)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1.apply(CometActor.scala:712)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2$$anonfun$apply$mcV$sp$1.apply(CometActor.scala:712)
net.liftweb.http.S$class.net$liftweb$http$S$$wrapQuery(S.scala:1470)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1$$anonfun$apply$37.apply(S.scala:1635)
net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1399)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$doAround$1.apply(S.scala:1400)
net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:244)
net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
net.liftweb.db.DB$$anon$2$$anonfun$apply$15$$anonfun$net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1$1.apply(DB.scala:260)
net.liftweb.db.DB$$anonfun$use$1.apply(DB.scala:701)
net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
net.liftweb.db.DB$currentConn$.run(DB.scala:686)
net.liftweb.db.DB$class.use(DB.scala:698)
net.liftweb.db.DB$$anon$1.use(DB.scala:40)
net.liftweb.db.DB$$anon$2$$anonfun$apply$15.net$liftweb$db$DB$class$$anon$$anonfun$$recurseMe$1(DB.scala:260)
net.liftweb.db.DB$$anon$2$$anonfun$apply$15.apply(DB.scala:262)
net.liftweb.util.DynoVar$class.run(ThreadGlobal.scala:95)
net.liftweb.db.DB$$anon$2$DepthCnt$.run(DB.scala:233)
net.liftweb.db.DB$$anon$2.apply(DB.scala:236)
net.liftweb.http.S$class.net$liftweb$http$S$$doAround(S.scala:1400)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_nest2InnerInit$1.apply(S.scala:1633)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$class.net$liftweb$http$S$$_nest2InnerInit(S.scala:1632)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$44.apply(S.scala:1676)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$$anonfun$withReq$1.apply(S.scala:1686)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$class.withReq(S.scala:1685)
net.liftweb.http.S$.withReq(S.scala:47)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42$$anonfun$apply$43.apply(S.scala:1672)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41$$anonfun$apply$42.apply(S.scala:1670)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1$$anonfun$apply$41.apply(S.scala:1669)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_innerInit$1.apply(S.scala:1668)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$class.net$liftweb$http$S$$_innerInit(S.scala:1667)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50$$anonfun$apply$51.apply(S.scala:1709)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50.apply(S.scala:1707)
net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
net.liftweb.http.RequestVarHandler$.apply(Vars.scala:507)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49.apply(S.scala:1706)
net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18$$anonfun$apply$19.apply(Vars.scala:611)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17$$anonfun$apply$18.apply(Vars.scala:610)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16$$anonfun$apply$17.apply(Vars.scala:609)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CoreRequestVarHandler$$anonfun$apply$16.apply(Vars.scala:608)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CoreRequestVarHandler$class.apply(Vars.scala:607)
net.liftweb.http.TransientRequestVarHandler$.apply(Vars.scala:520)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47$$anonfun$apply$48.apply(S.scala:1705)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1$$anonfun$apply$47.apply(S.scala:1704)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$$anonfun$net$liftweb$http$S$$_init$1.apply(S.scala:1703)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.S$class.net$liftweb$http$S$$_init(S.scala:1702)
net.liftweb.http.S$class.init(S.scala:1284)
net.liftweb.http.S$.init(S.scala:47)
net.liftweb.http.S$class.initIfUninitted(S.scala:2110)
net.liftweb.http.S$.initIfUninitted(S.scala:47)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2.apply$mcV$sp(CometActor.scala:711)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2.apply(CometActor.scala:711)
net.liftweb.http.CometActor$$anon$1$$anonfun$apply$2.apply(CometActor.scala:711)
net.liftweb.util.ThreadGlobal.doWith(ThreadGlobal.scala:71)
net.liftweb.http.CometActor$$anon$1.apply(CometActor.scala:710)
net.liftweb.http.CometActor$$anon$1.apply(CometActor.scala:708)
net.liftweb.actor.LiftActor$class.execTranslate(LiftActor.scala:502)
code.comet.MatchingJourneysCometActor.execTranslate(MatchingJourneysCometActor.scala:17)
net.liftweb.actor.SpecializedLiftActor$class.net$liftweb$actor$SpecializedLiftActor$$proc2(LiftActor.scala:305)
net.liftweb.actor.SpecializedLiftActor$$anonfun$net$liftweb$actor$SpecializedLiftActor$$processMailbox$1.apply$mcV$sp(LiftActor.scala:227)
net.liftweb.actor.SpecializedLiftActor$$anonfun$net$liftweb$actor$SpecializedLiftActor$$processMailbox$1.apply(LiftActor.scala:227)
net.liftweb.actor.SpecializedLiftActor$$anonfun$net$liftweb$actor$SpecializedLiftActor$$processMailbox$1.apply(LiftActor.scala:227)
net.liftweb.actor.SpecializedLiftActor$class.around(LiftActor.scala:241)
code.comet.MatchingJourneysCometActor.around(MatchingJourneysCometActor.scala:17)
net.liftweb.actor.SpecializedLiftActor$class.net$liftweb$actor$SpecializedLiftActor$$processMailbox(LiftActor.scala:226)
net.liftweb.actor.SpecializedLiftActor$$anonfun$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(LiftActor.scala:190)
net.liftweb.actor.LAScheduler$$anonfun$9$$anon$2$$anon$3.run(LiftActor.scala:76)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)

**Comment by kipperjim** [comment]
My code is simply 

scalaj.http.Http("https://svcs.sandbox.paypal.com/AdaptivePayments/Pay").option(HttpOptions.connTimeout(1000)).option(HttpOptions.readTimeout(5000)).asParams

Let me know if any more info is helpful.

Thanks!

**Comment by hoffrocket** [comment]
Hi, you've come across an interesting problem, but I think it's much lower level than this library. I don't see a problem using oracle java 1.8.0_60 on OSX, but I do see a problem using openssl 0.9.8zg on the same machine.

Here's the output from openssl 0.9.8zg:
```
openssl s_client -debug -connect svcs.sandbox.paypal.com:443
CONNECTED(00000003)
write to 0x7f8e32701020 [0x7f8e33803000] (130 bytes => 130 (0x82))
0000 - 80 80 01 03 01 00 57 00-00 00 20 00 00 39 00 00   ......W... ..9..
0010 - 38 00 00 35 00 00 16 00-00 13 00 00 0a 07 00 c0   8..5............
0020 - 00 00 33 00 00 32 00 00-2f 00 00 9a 00 00 99 00   ..3..2../.......
0030 - 00 96 03 00 80 00 00 05-00 00 04 01 00 80 00 00   ................
0040 - 15 00 00 12 00 00 09 06-00 40 00 00 14 00 00 11   .........@......
0050 - 00 00 08 00 00 06 04 00-80 00 00 03 02 00 80 00   ................
0060 - 00 ff b9 c8 a2 c1 e3 cc-e0 5d aa 4c 1a 12 7e 24   .........].L..~$
0070 - a7 ea 07 cc 10 df 60 62-62 5e b4 87 05 76 44 04   ......`bb^...vD.
0080 - db ff                                             ..
read from 0x7f8e32701020 [0x7f8e33808600] (7 bytes => 7 (0x7))
0000 - 15 03 01 00 02 02 28                              ......(
67658:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.40.1/src/ssl/s23_clnt.c:593:
```

openssl 1.0.1e on a different system doesn't get a handshake failure. It's possible that older versions of openssl had a bug, and your java version is built against one of those versions.  You might want to try upgrading to the latest version of java.

Let me know what you discover.

**Comment by hoffrocket** [comment]
Also, you might want to contact paypal and send them that openssl output. They'd probably be interested to know there's an issue with some versions of openssl and maybe they can make changes on their end.

**Comment by hoffrocket** [comment]
I dug into this a bit more, and it looks like paypal's server is configured to only support a newer set of SSL cipher suites. So, you're best bet is probably to upgrade java. You can see a full analysis of which ciphers paypal supports here: https://globalsign.ssllabs.com/analyze.html?d=svcs.sandbox.paypal.com

You can then compare that to what's available in your version of java: javax.net.ssl.SSLContext.getDefault.getSocketFactory.getSupportedCipherSuites

**Comment by kipperjim** [comment]
That's unbelievably helpful, thank you so much!
