### ISSUE TITLE
Chunked responses

### ISSUE THREAD

**Issue by IntelligyScience** [scalaj/scalaj-http#89]
Hi!

Play 2.4 provides chunked response. Using scalaj Http 2.0.0 with normal get. 

```
def index = Action {
  val data = getDataStream
  val dataContent: Enumerator[Array[Byte]] = Enumerator.fromStream(data)
  
  Ok.chunked(dataContent)
}
```

I always get the error
**The response to this request is chunked and hence requires HTTP 1.1 to be sent, but this is a HTTP 1.0 request.**

Someone any idea?

**Comment by hoffrocket** [comment]
Could this be an issue with your proxy? https://medium.com/@yatskevich/chunked-responses-with-nginx-and-play-framework-3ffada39ea0c#.2h6sq22p5

**Comment by IntelligyScience** [comment]
YEAH!!!!! You are me hero :+1: 
Absolutly!!!! I am happy now. I never mind nginx so I would had spent hours of wasting time!!!! Thanks Thanks thanks :)
