### ISSUE TITLE
Support Boolean as a data type for parameter value 

### ISSUE THREAD

**Issue by sangshu** [scalaj/scalaj-http#95]
Big fun of the api. Need one thing, can you add boolean support in the parameter? For example, I need to post payload like this:  { "is_autoPay":true} instead of {"is_autoPay":"true"}. I don't think I can do this now? or I missed anything? Thanks

**Comment by hoffrocket** [comment]
Hi, you can post a JSON string like this: `Http(url).postData("{\"is_autoPay\":\"true\"}")` 
Is that what you want?
