### ISSUE TITLE
No support for PUT

### ISSUE THREAD

**Issue by matanster** [scalaj/scalaj-http#96]
It is impossible to get through a PUT request having a body. 
hacking `.method("PUT")` with `.postData` turns the request into a POST request. Wonder how this hasn't come up before, I must be missing something but this is what reading the code and trying it out tells me.

**Comment by hoffrocket** [comment]
Hi,

I think the issue is that .postData changes the method. If you change
function call order and do postData.method it should do the correct thing.

**Comment by matanster** [comment]
Well you'll excuse me for saying this but I can't really see the point of
having a method called postData necessary for any request that sends a
body... changing the order of method application just highlights how much
that notion is an api no no doesn't it...

**Comment by hoffrocket** [comment]
Yes, you're definitely correct. That's a flaw in the API design

**Comment by matanster** [comment]
Seen my humble pull request?

Sent from my mobile

-------- Original Message --------
