### ISSUE TITLE
Support for SSE (Server-Sent-Events)

### ISSUE THREAD

**Issue by Antwnis** [scalaj/scalaj-http#98]
I love `scalaj-http` and for it to be a *fully featured http client for Scala* it needs to support *sse*.

i.e. i would like to use scalaj-http to connect to [marathon event-streams] (https://mesosphere.github.io/marathon/docs/rest-api.html#event-stream) 

and effectively send a GET request into a URL i.e.

    https://marathon.xxx.com/v2/events

And periodically fetch back events - as they occur

**Comment by hoffrocket** [comment]
Hi,

You can use the `execute` method to read directly from the chunked stream for as long as the connection is active. You will probably want to wrap the code in a loop so that it reconnects when the connection is lost:

```scala
while (true) {
  Http("http://httpbin.org/stream/20").execute(is => {
    scala.io.Source.fromInputStream(is).getLines.foreach(println))
  })
}

**Comment by Antwnis** [comment]
Thanks a bunch @hoffrocket 

      Http("https://marathon.landoop.com/v2/events")
        .header("Accept", "text/event-stream")
        .auth(MyConfiguration.marathonBasicUser, MyConfiguration.marathonBasicPass)
        .option(HttpOptions.allowUnsafeSSL)
        .option(HttpOptions.readTimeout(0))
        .execute(is => {
          scala.io.Source.fromInputStream(is).getLines().foreach(println)
        })

The only missing part in your reply was the `.option(HttpOptions.readTimeout(0))` and also setting to `text/event-stream` 

Would you like to add a small doc section in readme.md regarding server-sent-events ?
