### ISSUE TITLE
'charset' provided by 'Content-Type' header is ignored

### ISSUE THREAD

**Issue by JustAHappyKid** [scalaj/scalaj-http#99]
Sorry for not providing a proper pull request, but that probably wouldn't work because the test framework in use by this library [apparently does not support adding headers to the HTTP responses](https://github.com/scalaj/scalaj-http/issues/92). But I'm [attaching a test-case](https://github.com/scalaj/scalaj-http/files/200645/ScalajContentTypeBugSpec.scala.txt) that illustrates the problem.

Basically, if a website uses a non-`UTF-8` character encoding, and if it actually leverages the non-ASCII characters in that encoding, then `scalaj-http` will not correctly decode the content (as it assumes `UTF-8`).

**Comment by hoffrocket** [comment]
Thanks for reporting, I just pushed out a 2.2.2 release with the fix.

**Comment by JustAHappyKid** [comment]
No problem. Thanks for fix/update.
